import { useMemo, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { ArrowLeft, BookOpen, Check, ChevronRight, ClipboardList, Edit3, GraduationCap, LayoutDashboard, LibraryBig, LogOut, Menu, Plus, Search, ShieldCheck, Trash2, X } from 'lucide-react'
import './App.css'

type Role = 'student' | 'admin'
type Screen = 'admin-dashboard' | 'subjects' | 'questions' | 'student-preview'
type Subject = { id: number; name: string; description: string; topics: number }
type Topic = { id: number; name: string; subjectId: number }
type Question = { id: number; statement: string; subjectId: number; topicId: number; alternatives: string[]; correctIndex: number; status: 'Ativa' | 'Rascunho' }

const initialSubjects: Subject[] = [
  { id: 1, name: 'Matemática', description: 'Raciocínio lógico e cálculos.', topics: 3 },
  { id: 2, name: 'Português', description: 'Gramática, interpretação e redação.', topics: 2 },
  { id: 3, name: 'História', description: 'História do Brasil e geral.', topics: 2 },
]
const initialTopics: Topic[] = [
  { id: 1, name: 'Porcentagem', subjectId: 1 }, { id: 2, name: 'Equações', subjectId: 1 }, { id: 3, name: 'Geometria', subjectId: 1 },
  { id: 4, name: 'Interpretação de texto', subjectId: 2 }, { id: 5, name: 'Ortografia', subjectId: 2 },
  { id: 6, name: 'Brasil República', subjectId: 3 }, { id: 7, name: 'Revolução Industrial', subjectId: 3 },
]
const initialQuestions: Question[] = [
  { id: 1, statement: 'Um produto de R$ 200,00 recebeu desconto de 15%. Qual é o novo preço?', subjectId: 1, topicId: 1, alternatives: ['R$ 170,00', 'R$ 175,00', 'R$ 185,00', 'R$ 190,00'], correctIndex: 1, status: 'Ativa' },
  { id: 2, statement: 'Assinale a alternativa em que todas as palavras estão grafadas corretamente.', subjectId: 2, topicId: 5, alternatives: ['Exceção e privilégio', 'Excessão e previlégio', 'Exceção e previlégio', 'Excessão e privilégio'], correctIndex: 0, status: 'Ativa' },
]

function App() {
  const [role, setRole] = useState<Role | null>(null)
  const [screen, setScreen] = useState<Screen>('admin-dashboard')
  const [subjects, setSubjects] = useState(initialSubjects)
  const [topics, setTopics] = useState(initialTopics)
  const [questions, setQuestions] = useState(initialQuestions)
  const [isSidebarOpen, setSidebarOpen] = useState(false)
  const [notice, setNotice] = useState('')
  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 3200) }
  if (!role) return <Login onEnter={(nextRole) => { setRole(nextRole); setScreen(nextRole === 'admin' ? 'admin-dashboard' : 'student-preview') }} />
  const logout = () => { setRole(null); setSidebarOpen(false); setNotice('') }
  if (role === 'student') return <StudentPreview onLogout={logout} onAdminDemo={() => { setRole('admin'); setScreen('admin-dashboard') }} />
  const screenContent: Record<Exclude<Screen, 'student-preview'>, ReactNode> = {
    'admin-dashboard': <AdminDashboard subjects={subjects} topics={topics} questions={questions} goTo={setScreen} />,
    subjects: <SubjectsPage subjects={subjects} setSubjects={setSubjects} topics={topics} setTopics={setTopics} flash={flash} />,
    questions: <QuestionsPage subjects={subjects} topics={topics} questions={questions} setQuestions={setQuestions} flash={flash} />,
  }
  return <div className="app-shell"><Sidebar active={screen} onNavigate={(next) => { setScreen(next); setSidebarOpen(false) }} onLogout={logout} isOpen={isSidebarOpen} />{isSidebarOpen && <button className="backdrop" aria-label="Fechar menu" onClick={() => setSidebarOpen(false)} />}<main className="main-content"><Topbar onMenu={() => setSidebarOpen(true)} onLogout={logout} /><div className="page-content">{screenContent[screen as Exclude<Screen, 'student-preview'>]}</div></main>{notice && <div className="toast"><Check size={18} /> {notice}</div>}</div>
}

function Brand() { return <div className="brand"><div className="brand-mark"><GraduationCap size={23} /></div><span>Simula<span>AI</span></span></div> }

function Login({ onEnter }: { onEnter: (role: Role) => void }) {
  const [selectedRole, setSelectedRole] = useState<Role>('student')
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('')
  const submit = (event: FormEvent) => { event.preventDefault(); if (!email.trim() || !password.trim()) return setError('Preencha e-mail e senha para continuar.'); setError(''); onEnter(selectedRole) }
  return <main className="login-page"><section className="login-hero"><Brand /><div><span className="eyebrow light">PLATAFORMA DE ESTUDOS</span><h1>Prepare-se para<br />o seu próximo desafio.</h1><p>Crie simulados, acompanhe resultados e transforme seus erros em aprendizado.</p></div><div className="login-benefits"><span><Check size={16} /> Simulados organizados por assunto</span><span><Check size={16} /> Análise clara do seu desempenho</span><span><Check size={16} /> Explicações com apoio de IA</span></div></section><section className="login-panel"><form className="login-card" onSubmit={submit}><div><span className="eyebrow">BEM-VINDO</span><h2>Acesse sua conta</h2><p>Entre para continuar seus estudos.</p></div><div className="role-switch" aria-label="Perfil de acesso"><button className={selectedRole === 'student' ? 'selected' : ''} type="button" onClick={() => setSelectedRole('student')}><GraduationCap size={17} /> Aluno</button><button className={selectedRole === 'admin' ? 'selected' : ''} type="button" onClick={() => setSelectedRole('admin')}><ShieldCheck size={17} /> Administrador</button></div><label>E-mail<input value={email} onChange={(e) => setEmail(e.target.value)} type="email" placeholder="voce@email.com" autoComplete="email" /></label><label>Senha<input value={password} onChange={(e) => setPassword(e.target.value)} type="password" placeholder="Digite sua senha" autoComplete="current-password" /></label>{error && <p className="form-error">{error}</p>}<button className="button primary full" type="submit">Entrar <ChevronRight size={18} /></button><p className="demo-hint">Demonstração: escolha o perfil e informe qualquer e-mail e senha.</p></form></section></main>
}

function Sidebar({ active, onNavigate, onLogout, isOpen }: { active: Screen; onNavigate: (screen: Screen) => void; onLogout: () => void; isOpen: boolean }) {
  const items: { screen: Exclude<Screen, 'student-preview'>; label: string; icon: ReactNode }[] = [{ screen: 'admin-dashboard', label: 'Visão geral', icon: <LayoutDashboard size={19} /> }, { screen: 'subjects', label: 'Matérias e assuntos', icon: <LibraryBig size={19} /> }, { screen: 'questions', label: 'Questões', icon: <ClipboardList size={19} /> }]
  return <aside className={`sidebar ${isOpen ? 'open' : ''}`}><div><Brand /><p className="sidebar-role"><ShieldCheck size={15} /> Área administrativa</p></div><nav>{items.map((item) => <button key={item.screen} onClick={() => onNavigate(item.screen)} className={active === item.screen ? 'active' : ''}>{item.icon}{item.label}</button>)}</nav><div className="sidebar-footer"><div className="user-mini"><span className="avatar">AD</span><span><strong>Administrador</strong><small>Gestão do conteúdo</small></span></div><button className="logout" onClick={onLogout}><LogOut size={18} /> Sair</button></div></aside>
}
function Topbar({ onMenu, onLogout }: { onMenu: () => void; onLogout: () => void }) { return <header className="topbar"><button className="menu-button" onClick={onMenu} aria-label="Abrir menu"><Menu size={22} /></button><div className="breadcrumb">Administração <ChevronRight size={16} /> <strong>SimulaAI</strong></div><button className="mobile-logout" onClick={onLogout}><LogOut size={18} /></button></header> }

function AdminDashboard({ subjects, topics, questions, goTo }: { subjects: Subject[]; topics: Topic[]; questions: Question[]; goTo: (screen: Screen) => void }) {
  const activeQuestions = questions.filter((question) => question.status === 'Ativa').length
  return <><section className="page-heading"><div><span className="eyebrow">PAINEL ADMINISTRATIVO</span><h1>Olá, Administrador</h1><p>Gerencie os conteúdos que farão parte dos simulados.</p></div><span className="date-label">Sprint 1 · Conteúdo acadêmico</span></section><section className="metric-grid"><Metric icon={<BookOpen />} number={subjects.length} label="Matérias cadastradas" tone="blue" /><Metric icon={<LibraryBig />} number={topics.length} label="Assuntos organizados" tone="purple" /><Metric icon={<ClipboardList />} number={activeQuestions} label="Questões ativas" tone="green" /></section><section className="action-panel"><div><h2>Conteúdo pronto para começar</h2><p>Cadastre matérias, crie assuntos e monte o banco de questões do SimulaAI.</p></div><div className="action-buttons"><button className="button secondary" onClick={() => goTo('subjects')}><LibraryBig size={18} /> Gerenciar conteúdos</button><button className="button primary" onClick={() => goTo('questions')}><Plus size={18} /> Nova questão</button></div></section><section className="dashboard-columns"><article className="panel"><div className="panel-header"><div><h2>Matérias cadastradas</h2><p>Organize a base dos seus simulados.</p></div><button className="text-button" onClick={() => goTo('subjects')}>Ver todas <ChevronRight size={16} /></button></div><div className="subject-list">{subjects.map((subject) => <div className="subject-row" key={subject.id}><span className="subject-icon"><BookOpen size={18} /></span><span><strong>{subject.name}</strong><small>{topics.filter((topic) => topic.subjectId === subject.id).length} assuntos</small></span><ChevronRight size={18} /></div>)}</div></article><article className="panel"><div className="panel-header"><div><h2>Próximos passos</h2><p>Roteiro da Sprint 1.</p></div></div><ol className="steps"><li className="complete"><span><Check size={15} /></span><div><strong>Autenticação por perfil</strong><small>Fluxo visual de aluno e administrador.</small></div></li><li><span>2</span><div><strong>Estruturar conteúdos</strong><small>Cadastre matérias e seus assuntos.</small></div></li><li><span>3</span><div><strong>Montar questões</strong><small>Defina alternativas e uma resposta correta.</small></div></li></ol></article></section></>
}
function Metric({ icon, number, label, tone }: { icon: ReactNode; number: number; label: string; tone: string }) { return <article className={`metric-card ${tone}`}><span className="metric-icon">{icon}</span><div><strong>{number}</strong><span>{label}</span></div></article> }

function SubjectsPage({ subjects, setSubjects, topics, setTopics, flash }: { subjects: Subject[]; setSubjects: (items: Subject[]) => void; topics: Topic[]; setTopics: (items: Topic[]) => void; flash: (message: string) => void }) {
  const [subjectModal, setSubjectModal] = useState(false); const [topicModal, setTopicModal] = useState(false); const [editingSubject, setEditingSubject] = useState<Subject | null>(null); const [editingTopic, setEditingTopic] = useState<Topic | null>(null)
  const deleteSubject = (subject: Subject) => { if (!window.confirm(`Remover a matéria “${subject.name}” e seus assuntos?`)) return; setSubjects(subjects.filter((item) => item.id !== subject.id)); setTopics(topics.filter((item) => item.subjectId !== subject.id)); flash('Matéria removida com seus assuntos vinculados.') }
  const deleteTopic = (topic: Topic) => { if (!window.confirm(`Remover o assunto “${topic.name}”?`)) return; setTopics(topics.filter((item) => item.id !== topic.id)); flash('Assunto removido com sucesso.') }
  return <><section className="page-heading"><div><span className="eyebrow">ORGANIZAÇÃO DO CONTEÚDO</span><h1>Matérias e assuntos</h1><p>Crie a estrutura que será usada para organizar as questões.</p></div><div className="heading-actions"><button className="button secondary" onClick={() => { setEditingTopic(null); setTopicModal(true) }}><Plus size={18} /> Novo assunto</button><button className="button primary" onClick={() => { setEditingSubject(null); setSubjectModal(true) }}><Plus size={18} /> Nova matéria</button></div></section><section className="content-grid two"><article className="panel"><div className="panel-header"><div><h2>Matérias</h2><p>{subjects.length} cadastradas</p></div></div><div className="data-list">{subjects.map((subject) => <div className="data-row" key={subject.id}><div><strong>{subject.name}</strong><small>{subject.description}</small></div><span className="count-badge">{topics.filter((topic) => topic.subjectId === subject.id).length} assuntos</span><div className="row-actions"><button aria-label={`Editar ${subject.name}`} onClick={() => { setEditingSubject(subject); setSubjectModal(true) }}><Edit3 size={16} /></button><button className="danger" aria-label={`Excluir ${subject.name}`} onClick={() => deleteSubject(subject)}><Trash2 size={16} /></button></div></div>)}</div></article><article className="panel"><div className="panel-header"><div><h2>Assuntos</h2><p>{topics.length} cadastrados</p></div></div><div className="data-list">{topics.map((topic) => <div className="data-row compact" key={topic.id}><div><strong>{topic.name}</strong><small>{subjects.find((subject) => subject.id === topic.subjectId)?.name ?? 'Matéria removida'}</small></div><div className="row-actions"><button aria-label={`Editar ${topic.name}`} onClick={() => { setEditingTopic(topic); setTopicModal(true) }}><Edit3 size={16} /></button><button className="danger" aria-label={`Excluir ${topic.name}`} onClick={() => deleteTopic(topic)}><Trash2 size={16} /></button></div></div>)}</div></article></section>{subjectModal && <SubjectModal subject={editingSubject} onClose={() => setSubjectModal(false)} onSave={(data) => { if (editingSubject) { setSubjects(subjects.map((item) => item.id === editingSubject.id ? { ...item, ...data } : item)); flash('Matéria atualizada com sucesso.') } else { setSubjects([...subjects, { ...data, id: Math.max(0, ...subjects.map((item) => item.id)) + 1, topics: 0 }]); flash('Matéria cadastrada com sucesso.') } setSubjectModal(false) }} />}{topicModal && <TopicModal topic={editingTopic} subjects={subjects} onClose={() => setTopicModal(false)} onSave={(data) => { if (editingTopic) { setTopics(topics.map((item) => item.id === editingTopic.id ? { ...item, ...data } : item)); flash('Assunto atualizado com sucesso.') } else { setTopics([...topics, { ...data, id: Math.max(0, ...topics.map((item) => item.id)) + 1 }]); flash('Assunto cadastrado com sucesso.') } setTopicModal(false) }} />}</>
}

function QuestionsPage({ subjects, topics, questions, setQuestions, flash }: { subjects: Subject[]; topics: Topic[]; questions: Question[]; setQuestions: (items: Question[]) => void; flash: (message: string) => void }) {
  const [modal, setModal] = useState(false); const [editing, setEditing] = useState<Question | null>(null); const [search, setSearch] = useState(''); const visibleQuestions = useMemo(() => questions.filter((question) => question.statement.toLocaleLowerCase().includes(search.toLocaleLowerCase())), [questions, search])
  return <><section className="page-heading"><div><span className="eyebrow">BANCO DE QUESTÕES</span><h1>Questões e alternativas</h1><p>Cadastre perguntas objetivas e marque uma única resposta correta.</p></div><button className="button primary" onClick={() => { setEditing(null); setModal(true) }}><Plus size={18} /> Nova questão</button></section><section className="panel question-panel"><div className="table-toolbar"><div><h2>Questões cadastradas</h2><p>{questions.length} questões no banco</p></div><label className="search"><Search size={18} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por enunciado" /></label></div><div className="table-wrap"><table><thead><tr><th>Questão</th><th>Matéria</th><th>Assunto</th><th>Status</th><th aria-label="Ações" /></tr></thead><tbody>{visibleQuestions.map((question) => <tr key={question.id}><td><strong>{question.statement}</strong><small>{question.alternatives.length} alternativas · correta: {String.fromCharCode(65 + question.correctIndex)}</small></td><td>{subjects.find((subject) => subject.id === question.subjectId)?.name ?? '—'}</td><td>{topics.find((topic) => topic.id === question.topicId)?.name ?? '—'}</td><td><span className={`status ${question.status === 'Ativa' ? 'active' : ''}`}>{question.status}</span></td><td className="row-actions"><button aria-label="Editar questão" onClick={() => { setEditing(question); setModal(true) }}><Edit3 size={16} /></button><button className="danger" aria-label="Excluir questão" onClick={() => { if (window.confirm('Excluir esta questão?')) { setQuestions(questions.filter((item) => item.id !== question.id)); flash('Questão excluída com sucesso.') } }}><Trash2 size={16} /></button></td></tr>)}{visibleQuestions.length === 0 && <tr><td className="empty" colSpan={5}>Nenhuma questão encontrada.</td></tr>}</tbody></table></div></section>{modal && <QuestionModal question={editing} subjects={subjects} topics={topics} onClose={() => setModal(false)} onSave={(data) => { if (editing) { setQuestions(questions.map((item) => item.id === editing.id ? { ...item, ...data } : item)); flash('Questão atualizada com sucesso.') } else { setQuestions([...questions, { ...data, id: Math.max(0, ...questions.map((item) => item.id)) + 1 }]); flash('Questão cadastrada com sucesso.') } setModal(false) }} />}</>
}

function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="modal-layer" role="dialog" aria-modal="true" aria-label={title}><div className="modal"><header><h2>{title}</h2><button onClick={onClose} aria-label="Fechar"><X size={20} /></button></header>{children}</div></div> }
function SubjectModal({ subject, onClose, onSave }: { subject: Subject | null; onClose: () => void; onSave: (data: Pick<Subject, 'name' | 'description'>) => void }) { const [name, setName] = useState(subject?.name ?? ''); const [description, setDescription] = useState(subject?.description ?? ''); const [error, setError] = useState(''); return <Modal title={subject ? 'Editar matéria' : 'Nova matéria'} onClose={onClose}><form className="modal-form" onSubmit={(event) => { event.preventDefault(); if (!name.trim()) return setError('O nome da matéria é obrigatório.'); onSave({ name: name.trim(), description: description.trim() }) }}><label>Nome da matéria<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Ex.: Matemática" /></label><label>Descrição<input value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Descrição opcional" /></label>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button className="button ghost" type="button" onClick={onClose}>Cancelar</button><button className="button primary" type="submit">Salvar matéria</button></div></form></Modal> }
function TopicModal({ topic, subjects, onClose, onSave }: { topic: Topic | null; subjects: Subject[]; onClose: () => void; onSave: (data: Pick<Topic, 'name' | 'subjectId'>) => void }) { const [name, setName] = useState(topic?.name ?? ''); const [subjectId, setSubjectId] = useState(topic?.subjectId ?? subjects[0]?.id ?? 0); const [error, setError] = useState(''); return <Modal title={topic ? 'Editar assunto' : 'Novo assunto'} onClose={onClose}><form className="modal-form" onSubmit={(event) => { event.preventDefault(); if (!name.trim() || !subjectId) return setError('Informe o nome e a matéria do assunto.'); onSave({ name: name.trim(), subjectId }) }}><label>Matéria<select value={subjectId} onChange={(event) => setSubjectId(Number(event.target.value))}><option value={0}>Selecione uma matéria</option>{subjects.map((subject) => <option value={subject.id} key={subject.id}>{subject.name}</option>)}</select></label><label>Nome do assunto<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Ex.: Porcentagem" /></label>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button className="button ghost" type="button" onClick={onClose}>Cancelar</button><button className="button primary" type="submit">Salvar assunto</button></div></form></Modal> }
function QuestionModal({ question, subjects, topics, onClose, onSave }: { question: Question | null; subjects: Subject[]; topics: Topic[]; onClose: () => void; onSave: (data: Omit<Question, 'id'>) => void }) {
  const [statement, setStatement] = useState(question?.statement ?? ''); const [subjectId, setSubjectId] = useState(question?.subjectId ?? subjects[0]?.id ?? 0); const [topicId, setTopicId] = useState(question?.topicId ?? topics.find((topic) => topic.subjectId === subjects[0]?.id)?.id ?? 0); const [alternatives, setAlternatives] = useState(question?.alternatives ?? ['', '', '', '']); const [correctIndex, setCorrectIndex] = useState(question?.correctIndex ?? 0); const [status, setStatus] = useState<Question['status']>(question?.status ?? 'Ativa'); const [error, setError] = useState(''); const availableTopics = topics.filter((topic) => topic.subjectId === subjectId)
  const changeSubject = (id: number) => { setSubjectId(id); setTopicId(topics.find((topic) => topic.subjectId === id)?.id ?? 0) }; const updateAlternative = (index: number, value: string) => setAlternatives(alternatives.map((alternative, itemIndex) => itemIndex === index ? value : alternative)); const submit = (event: FormEvent) => { event.preventDefault(); if (!statement.trim() || !subjectId || !topicId || alternatives.some((alternative) => !alternative.trim())) return setError('Preencha o enunciado, a organização e todas as alternativas.'); onSave({ statement: statement.trim(), subjectId, topicId, alternatives: alternatives.map((alternative) => alternative.trim()), correctIndex, status }) }
  return <Modal title={question ? 'Editar questão' : 'Nova questão'} onClose={onClose}><form className="modal-form question-form" onSubmit={submit}><label>Enunciado<textarea autoFocus value={statement} onChange={(event) => setStatement(event.target.value)} placeholder="Digite o enunciado da questão" rows={3} /></label><div className="form-grid"><label>Matéria<select value={subjectId} onChange={(event) => changeSubject(Number(event.target.value))}>{subjects.map((subject) => <option value={subject.id} key={subject.id}>{subject.name}</option>)}</select></label><label>Assunto<select value={topicId} onChange={(event) => setTopicId(Number(event.target.value))}>{availableTopics.map((topic) => <option value={topic.id} key={topic.id}>{topic.name}</option>)}</select></label></div><fieldset><legend>Alternativas <span>Marque apenas uma correta.</span></legend>{alternatives.map((alternative, index) => <label className="alternative-input" key={index}><input type="radio" name="correct" checked={correctIndex === index} onChange={() => setCorrectIndex(index)} aria-label={`Definir alternativa ${String.fromCharCode(65 + index)} como correta`} /><span>{String.fromCharCode(65 + index)}</span><input value={alternative} onChange={(event) => updateAlternative(index, event.target.value)} placeholder={`Alternativa ${String.fromCharCode(65 + index)}`} /></label>)}</fieldset><label>Status<select value={status} onChange={(event) => setStatus(event.target.value as Question['status'])}><option>Ativa</option><option>Rascunho</option></select></label>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button className="button ghost" type="button" onClick={onClose}>Cancelar</button><button className="button primary" type="submit">{question ? 'Salvar alterações' : 'Cadastrar questão'}</button></div></form></Modal>
}
function StudentPreview({ onLogout, onAdminDemo }: { onLogout: () => void; onAdminDemo: () => void }) { return <main className="student-preview"><header><Brand /><button className="button ghost" onClick={onLogout}><LogOut size={17} /> Sair</button></header><section><span className="eyebrow">ÁREA DO ALUNO</span><h1>Seu acesso foi reconhecido.</h1><p>A interface de simulados, respostas, resultados e evolução será implementada nas Sprints 2 e 3, conforme o backlog priorizado.</p><div className="preview-cards"><article><ClipboardList /><strong>Realizar simulados</strong><span>Sprint 2</span></article><article><BookOpen /><strong>Resultados e explicações</strong><span>Sprint 2 e 3</span></article><article><LayoutDashboard /><strong>Desempenho e histórico</strong><span>Sprint 3</span></article></div><button className="button secondary" onClick={onAdminDemo}><ArrowLeft size={18} /> Abrir demonstração administrativa</button></section></main> }
export default App
